---
# Source: argo-workflows/templates/server/server-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-argo-workflows-server
  labels:
    helm.sh/chart: argo-workflows-0.42.2
    app.kubernetes.io/name: argo-workflows-server
    app.kubernetes.io/instance: argo
    app.kubernetes.io/component: server
    app: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-argo-workflows-server
subjects:
- kind: ServiceAccount
  name: argo-argo-workflows-server
  namespace: "argowf"
---
# Source: argo-workflows/templates/server/server-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-argo-workflows-server-cluster-template
  labels:
    helm.sh/chart: argo-workflows-0.42.2
    app.kubernetes.io/name: argo-workflows-server
    app.kubernetes.io/instance: argo
    app.kubernetes.io/component: server
    app: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-argo-workflows-server-cluster-template
subjects:
- kind: ServiceAccount
  name: argo-argo-workflows-server
  namespace: "argowf"
